### ISSUE TITLE
How do I use the API

### ISSUE THREAD

**Issue by molnsys** [fhqvst/avanza#15]
Hi,
can I use this API as an Avanza user and place orders? Are there some settings to be aware of in Avanza?

I am currently building a forecast service for the OMX Stockholm.

Regards,

Göran

**Comment by fhqvst** [comment]
Hi! 

Yes, you can use this to place, edit and cancel orders. There aren't any particular settings you need to worry about. 

Please have a look at the [API docs](https://github.com/fhqvst/avanza/blob/master/API.md) for usage instructions.
