### ISSUE TITLE
Trying  to make something like this in java to work. But im having problem with the authentication, any ideas on how to send a viable authentication?

### ISSUE THREAD

**Issue by MaxFre** [fhqvst/avanza#24]

**Comment by fhqvst** [comment]
Have a glance at [lib/totp.js](https://github.com/fhqvst/avanza/blob/master/lib/totp.js) and the `authenticate()` function in [lib/index.js](https://github.com/fhqvst/avanza/blob/master/lib/index.js). It is likely only a matter of translating javascript into java.
