### ISSUE TITLE
Stocks owned info

### ISSUE THREAD

**Issue by pontussalenbo** [fhqvst/avanza#25]
Is there any way for me to view all stocks owned on an account and get numbers owned, market value with this API?

**Comment by fhqvst** [comment]
Yes, `getPositions` is probably your best bet. Refer to [API.md](https://github.com/fhqvst/avanza/blob/master/API.md).

**Comment by pontussalenbo** [comment]
But from what I can understand this will only give me a brief summary of data. It doesnt retrieve that I own 4 Apple stocks with the value of 180$/each with 20% profitpercent or am I doing it wrong?
