### ISSUE TITLE
Regarding parameters

### ISSUE THREAD

**Issue by pontussalenbo** [fhqvst/avanza#26]
Hi,

I can't quite understand what some of the parameters are to be found, 
"
Your positions in an instrument. Expects a string of <orderbookId>_<accountId1>,<accountId2,<accountId3>,..."
Where do I find each of them on the avanza platform the easiest?

**Comment by fhqvst** [comment]
I guess the easiest way is by using the `getAccountOverview()` method. You'll receive a list of your accounts, including the ID of each account.
