### ISSUE TITLE
Unknown identifier?

### ISSUE THREAD

**Issue by matsalmstrom** [fhqvst/avanza#29]
Hi, 

I'm a noob on Node js. So most likely it is due to this.

I have installed the library and got the TOTP and registered the code i got running the command. Then I try to run the first example in the readme. But I only get; 

"SyntaxError: Unexpected identifier" 

complaining on "Avanza" in;

"import Avanza from 'avanza' "

Any idea?

**Comment by fhqvst** [comment]
Node does not yet support ES6 imports. Unless you want to use a transpiler such as Babel or a compiler such as tsc, you can always just import the library using `const Avanza = require('avanza')`.
