### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by pontussalenbo** [fhqvst/avanza#47]
I recently started to use this project and I stumbled across errors when using TOTP.
I followed the step by step in readme but when I submit the generated 6 digit code to Avanza it says that it is invalid while trying to activate 2FA, do you have an clue what I might be doing wrong?

**Comment by 3DJakob** [comment]
One possible problem could be that it expired. Make sure you submit it just after generating it. That worked for me.

**Comment by fhqvst** [comment]
Make sure you paste the secret correctly. Here's an example:
```sh
node -e "console.log(require('avanza/dist/totp')('K01BADBT3218UD'))"
```
