### ISSUE TITLE
Problem with subscribing to Channels with multiple arguments

### ISSUE THREAD

**Issue by sthlmjohan** [fhqvst/avanza#48]
Hi, 

Trying to subscribe to the Channels for real-time updates using the: POSITIONS, ORDERS and DEALS but I do not get any response back from these. I have double checked that I am sending all my accountIds that are retrieved using getOverview. Any idea what could be wrong, or what the correct syntax is?

Have there been any changes lately in the underlying API at Avanzas part?

Regards
/ Johan

**Comment by sthlmjohan** [comment]
Solved the problem. Apparently the order of the accounts matter for these function calls.

**Comment by paragloom** [comment]
> Solved the problem. Apparently the order of the accounts matter for these function calls.

@sthlmjohan could you elaborate on this order fix? I'm having the same issue.
