### ISSUE TITLE
OHLC Data for intraday

### ISSUE THREAD

**Issue by hrudelius** [fhqvst/avanza#5]
Hi,

I was hoping to use the API for pulling intraday data. 
The documentation for getChartdata indicates the result is "an array of OHLC data",
however when I try getting data for "TODAY" it only returns a single array (including "last trade price"?). Have I misunderstood something? Is there a way to get OHLC?

/hrudelius

**Comment by fhqvst** [comment]
No, you're correct, the documentation is faulty. As far as I know, there is no way of retrieving OHLC data.

**Comment by hrudelius** [comment]
Thanks, I know it's off topic but do you know if it's possible with the nordnet API? It (again) appears to be using "GET /next/2/tradables/intraday/{tradables}"?

**Comment by fhqvst** [comment]
I haven't used it myself, but [it seems like it would work](https://api.test.nordnet.se/api-docs/index.html#!/tradables/get_intraday_graph). If that doesn't do it, there are quite a few other resources which might have what you're looking for, such as [Quandl](https://www.quandl.com/), [VA Finans](http://www.vafinans.se/) or [4-traders](http://www.4-traders.com/).
