### ISSUE TITLE
Adding portfolio analysis API call

### ISSUE THREAD

**Issue by emmmile** [fhqvst/avanza#54]
Hello @fhqvst :)

I'm wondering how complicated would it be to add one method to return the information available under:

[Min ekonomi -> Analys -> Min fondportföljanalys](https://www.avanza.se/min-ekonomi/analys/fondportfoljanalys.html)

I can also try to extend the API myself, but maybe you can first give me some advice on where to start and what might be the complications.

Thanks!

**Comment by emmmile** [comment]
I'm closing this, as I found a way to do this using the `call` method.

**Comment by fhqvst** [comment]
Neat! Feel free to submit a PR if you think it could be useful for others
