### ISSUE TITLE
Cannot load due to access control checks

### ISSUE THREAD

**Issue by 3DJakob** [fhqvst/avanza#55]
I tried the sample code in your readme however I cannot seem to be able to connect to the server due to being on a different URL. Have they closed down the API to internal use only or am I missing something?

```
avanza.authenticate({
      username: 'myUserName',
      password: 'myPassword',
      totpSecret: 'mySecret'
}).then(async () => {
      const positions = await avanza.getPositions()
      console.log(positions)
})
```

![Screenshot 2021-01-21 at 13 54 15](https://user-images.githubusercontent.com/3826262/105353920-279fe100-5bf0-11eb-87e0-c65d0dfb127e.png)

**Comment by fhqvst** [comment]
Browsers do not allow you to connect to other origins. You'll have to run it on the server-side, or in a framework like [Electron](https://www.electronjs.org/).

**Comment by 3DJakob** [comment]
Yup thought so much. Got it working in electron 👍
