### ISSUE TITLE
Any idea how to interpret dealTime?

### ISSUE THREAD

**Issue by tarentula** [fhqvst/avanza#58]
First, I just want to say it's an awesome API wrapper! Great job!

Secondly, when subscribing to trades, the json objects returned includes a dealTime property like this: "dealTime":1615204638000

Do you know how to interpret the number? I'm not sure what to make of it or how to convert it to an actual time value that makes sense. Greatful for any hint.

**Comment by ausrasul** [comment]
Seems like timestamp in milliseconds.

**Comment by fhqvst** [comment]
That's correct, for your specific example: `1615204638000` -> `Mon Mar 08 2021 11:57:18 GMT+0000`

See https://en.wikipedia.org/wiki/Unix_time

**Comment by tarentula** [comment]
Ah, perfect. I feel I should have caught that one, but thanks for your quick aid!
