### ISSUE TITLE
Check if market is open

### ISSUE THREAD

**Issue by JakobWestergarden** [fhqvst/avanza#63]
Is there any function to check if the market is open for an instrument or a market as a whole? I know we can get tradable dates, and otherwise use Date() to see if the market _should_ be open, but this seems like a suboptimal solution since we might have halfdays and other unforeseen problems. Is there any function in the api which just returns if an instrument can have orders placed on it?

**Comment by ausrasul** [comment]
I import this schedule once a year and never had a problem.

https://www.avanza.se/aktier/oppettider-handelskalender.html

**Comment by JakobWestergarden** [comment]
> I import this schedule once a year and never had a problem.
> 
> https://www.avanza.se/aktier/oppettider-handelskalender.html

thank you! Is there an api function which can do this automatically or you manually import it?

**Comment by ausrasul** [comment]
I don’t know. Let me know if you find out.

**Comment by fhqvst** [comment]
IIRC, Avanza show no information about trading halts in the app, so for that you'd have to rely on another API, maybe subscribe to some Twitter account, or use this screen: https://www.nasdaqtrader.com/trader.aspx?id=TradeHalts.

For half-days etc. on the other hand, I _do_ think there's usually a banner at the top of the app UI, meaning we should be able to read that. Would require a bit of digging but nothing major.
