### ISSUE TITLE
Can't place orders

### ISSUE THREAD

**Issue by bellbrant** [fhqvst/avanza#77]
After avanzas update i can't place any orders anymore. 
"Method is unallowed"

Is there something we need to add regarding placing orders?

**Comment by dichai1983** [comment]
1. The constant `ORDER_PLACE_DELETE_PATH` should to be `/_cqbe/trading/order/new`
2. When you do `placeOrder`, the key of the orderType option should be `side`

I'll test the above 2 things this Friday.

**Comment by dichai1983** [comment]
Check out my fork: https://github.com/dichai1983/avanza-lib

**Comment by dichai1983** [comment]
Avanza changed their order placing servlet URI again today :( I will look into it.

**Comment by dichai1983** [comment]
Testing the new URI...

**Comment by dichai1983** [comment]
It's been fixed in my fork.

**Comment by fhqvst** [comment]
Awesome @dichai1983! Feel free to submit a PR

**Comment by bellbrant** [comment]
Late response but awesome work!!
